name: slender_parser
description: A parser for the Slender framework
version: 0.0.1
repository: https://github.com/exaby73/slender

environment:
  sdk: ^3.5.1

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
